USE [COBRANZA]
GO
/****** Object:  StoredProcedure [CLARO].[SP_PROCESO_DESCUENTO]    Script Date: 24/03/2026 20:59:49 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
		ALTER PROCEDURE [CLARO].[SP_PROCESO_DESCUENTO]
		AS
		BEGIN
		SET NOCOUNT ON


		DROP TABLE IF EXISTS #DESCUENTO_V2

DROP TABLE IF EXISTS #DESCUENTO_V3
DROP TABLE IF EXISTS #CONCRETADOS
DROP TABLE IF EXISTS #OFRECIDO
DROP TABLE IF EXISTS ##DESCUENTO_FINAL
DROP TABLE IF EXISTS ##NO_CUMPLE_CONCRETADO
DROP TABLE IF EXISTS ##AGENTE_CONCRETADO
DROP TABLE IF EXISTS #CLP_ESTADOS

CREATE TABLE #DESCUENTO_V2
(
[FECHA] NVARCHAR(255),
[MES] NVARCHAR(255),
[AÑO] NVARCHAR(255),
[CUST_ACCOUNT_ASIGNACION] NVARCHAR(255),
[RUC_DNI_ASIGNACION] NVARCHAR(255),
[NOMBRE_COMPLETO] NVARCHAR(255),
[SERVICIO] NVARCHAR(255),
[TECNOLOGIA] NVARCHAR(255),
[RECIBO] NVARCHAR(255),
[FECHA_EMISION] NVARCHAR(255),
[FECHA_VENCIMIENTO] NVARCHAR(255),
[IMPORTE_FACTURADO] NVARCHAR(255),
[SALDO_GESTIONADO] NVARCHAR(255),
[ETAPA] NVARCHAR(255),
[GESTOR] NVARCHAR(255),
[CARTERA] NVARCHAR(255),
[DESCUENTO] NVARCHAR(255),
[MONTO_PAGADO] NVARCHAR(255),
[SERVICIO_PLAN] NVARCHAR(255),
[ANTIGUEDAD] NVARCHAR(255),
[ACEPTO] NVARCHAR(255),
[AJUSTE_REALIZADO] NVARCHAR(255),
[FECHA_REGISTRO] NVARCHAR(255),
[OBSERVACIONES] NVARCHAR(255),
[BENEFICIO] NVARCHAR(255),
[DOC_DEFINITIVO] NVARCHAR(255),
[ACCION] NVARCHAR(255),
[FECHA_SALDO] NVARCHAR(255),
[CUST_ACCOUNT] NVARCHAR(255),
[RUC_DNI] NVARCHAR(255),
[PLAN_SERVICIO] NVARCHAR(255),
[TIPO_DOCUMENTO] NVARCHAR(255),
[NRO_DOCUMENTO] NVARCHAR(255),
[FEC_EMI] NVARCHAR(255),
[FEN_VENC] NVARCHAR(255),
[MONTO_ORIGINAL] NVARCHAR(255),
[RECLAMO] NVARCHAR(255),
[TOTAL_A_GESTIONAR_S] NVARCHAR(255),
[NOMBRE_CARTERA] NVARCHAR(255),
[SALDO] NVARCHAR(255),
[SALDO_SOLES] NVARCHAR(255),
[MONTO_RECLAMADO] NVARCHAR(255),
[MONEDA] NVARCHAR(255),
[MARCA] NVARCHAR(255),
[PAGO_TOTAL] NVARCHAR(255),
[FECHA_PAGO] NVARCHAR(255),
[FECHA_GESTION_DESDE_EL_INICIO_DE_CARTERA] NVARCHAR(255),
[HORA_GESTION_DESDE_EL_INICIO_DE_CARTERA] NVARCHAR(255),
[TIPO_CONTACTO_DESDE_EL_INICIO_DE_CARTERA] NVARCHAR(255),
[RESPUESTA_DESDE_EL_INICIO_DE_CARTERA] NVARCHAR(255),
[SUB_RESPUESTA_DESDE_EL_INICIO_DE_CARTERA] NVARCHAR(255),
[TELEFONO_DESDE_EL_INICIO_DE_CARTERA] NVARCHAR(255),
[COMENTARIO_DESDE_EL_INICIO_DE_CARTERA] NVARCHAR(255),
[AGENTE_DESDE_EL_INICIO_DE_CARTERA] NVARCHAR(255),
[FECHA_COMPROMISO_DESDE_EL_INICIO_DE_CARTERA] NVARCHAR(255),
[MONTO_COMPROMISO_DESDE_EL_INICIO_DE_CARTERA] NVARCHAR(255),
[PERFIL_CLIENTE] NVARCHAR(255),
[FECHA_INI] NVARCHAR(255),
[FECHA_FIN] NVARCHAR(255),
[CICLO] NVARCHAR(255),
[MOTIVO_DESCUENTO] NVARCHAR(255),
[PRODUCTO] NVARCHAR(255),
[PERMANENCIA_CLIENTE] NVARCHAR(255),
[FECHA_PAGO_SISTEMA] NVARCHAR(255),
[MONTO_PAGO] NVARCHAR(255),
[RENTA_BASICA] NVARCHAR(255)

)


SELECT CODIGO, NOMBRE_CARTERA, ESTADO_SERVICIO INTO #CLP_ESTADOS FROM CLARO.CLP_ESTADOS WITH(NOLOCK)
WHERE FECHA_CARGA = (SELECT MAX(FECHA_CARGA) FROM CLARO.CLP_ESTADOS WITH(NOLOCK))

CREATE INDEX INX_CLP_ESTADOS ON #CLP_ESTADOS (CODIGO, NOMBRE_CARTERA)
INCLUDE(ESTADO_SERVICIO)




	BULK INSERT #DESCUENTO_V2
		FROM 'T:\RUTA_PROYECTO\PROCESO DESCUENTO\CLP_IBR_DESCUENTO_V2.txt'
		WITH (
			FIRSTROW = 2,
			FIELDTERMINATOR = '|',
			ROWTERMINATOR = '\n',
			--FORMAT = 'CSV',
			FIELDQUOTE = '"'
		)
		
UPDATE #DESCUENTO_V2
SET DESCUENTO = '0'
WHERE TRY_CAST(DESCUENTO AS float) IS NULL 




		IF EXISTS (SELECT 1  FROM #DESCUENTO_V2
					WHERE FECHA_FIN IS  NULL )
			BEGIN 
			PRINT 'FALTA FECHA FIN'
			END
			ELSE 
			BEGIN
		SELECT * 
		INTO #DESCUENTO_V3
		FROM (
		SELECT *,
		CAST(DESCUENTO AS float) - CAST(SALDOS_SOLES_FINAL AS float) AS AJUSTE_OFRECIDO_MENOS_SALDO_SOLES
		
		FROM (
		SELECT A.*, 
		CASE WHEN CAST(PAGO.AMOUNT_APPLIED_SOLES AS money) = CAST(PAGO_TOTAL AS money) OR CAST(PAGO.AMOUNT_APPLIED_SOLES AS money) IS NULL
				  THEN SALDO_SOLES ELSE CAST(SALDO_SOLES AS MONEY) - CAST(PAGO.AMOUNT_APPLIED_SOLES AS money) END AS SALDOS_SOLES_FINAL,
				  PAGO.AMOUNT_APPLIED_SOLES AS PAGOS_CARGA_HOY
				  --PAGO.FECHA_PAGO_SISTEMA AS FECHA_PAGO_HOY
		
		FROM #DESCUENTO_V2 A
		LEFT JOIN (	SELECT TRX_NUMBER, NOMBRE_CARTERA, SUM(CAST(AMOUNT_APPLIED_SOLES AS MONEY)) AS AMOUNT_APPLIED_SOLES FROM (	
						SELECT * FROM (
					SELECT A.*, PAGO_TOTAL  FROM (SELECT TRX_NUMBER, NOMBRE_CARTERA, 
														CAST(A.FECHA_PAGO_SISTEMA AS date) AS FECHA_PAGO_SISTEMA,
														SUM(CAST(AMOUNT_APPLIED_SOLES AS MONEY)) AS AMOUNT_APPLIED_SOLES 
														FROM CLARO.PAGOS A WITH(NOLOCK)
														WHERE A.FECHA_CARGA = CAST(GETDATE() AS DATE) 
														AND A.NOMBRE_CARTERA NOT LIKE '%PJ%'
														AND A.NOMBRE_CARTERA NOT LIKE '%P_M%'
														AND A.NOMBRE_CARTERA NOT LIKE '%WHATSAPP%'
														AND A.NOMBRE_CARTERA NOT LIKE '%P_FIJA%'
														AND A.NOMBRE_CARTERA NOT LIKE '%P_CVE%'
														
														GROUP BY TRX_NUMBER, NOMBRE_CARTERA, CAST(A.FECHA_PAGO_SISTEMA AS date)) A
					LEFT JOIN (SELECT RECIBO, CARTERA, PAGO_TOTAL, FECHA_PAGO  FROM #DESCUENTO_V2
								WHERE FECHA_PAGO IS NOT NULL
								AND CAST(PAGO_TOTAL AS MONEY) >0) RET ON RET.RECIBO = A.TRX_NUMBER
																		AND RET.CARTERA = A.NOMBRE_CARTERA
																		AND RET.PAGO_TOTAL = A.AMOUNT_APPLIED_SOLES
																		AND CAST(RET.FECHA_PAGO AS date) = CAST(A.FECHA_PAGO_SISTEMA AS date)

							) AS PAGOS_CLARO
							WHERE PAGO_TOTAL IS NULL
							) AS PAGO_UNIDO
							GROUP BY TRX_NUMBER, NOMBRE_CARTERA
							) PAGO ON PAGO.TRX_NUMBER =A.RECIBO
									AND PAGO.NOMBRE_CARTERA =A.CARTERA
		
		
		) AS DESCUENTO_V2
		) AS DESCUENTO_V2
		--WHERE RECIBO IN('SB02-0226175839')
		WHERE AJUSTE_OFRECIDO_MENOS_SALDO_SOLES  >= -2
		AND CAST(SALDOS_SOLES_FINAL AS money) >= 5

		UPDATE #DESCUENTO_V3
		SET AJUSTE_REALIZADO = CASE WHEN AJUSTE_OFRECIDO_MENOS_SALDO_SOLES  >= -2 AND AJUSTE_OFRECIDO_MENOS_SALDO_SOLES  <0  THEN DESCUENTO ELSE AJUSTE_REALIZADO END 


		SELECT * 
		INTO #CONCRETADOS 
		FROM (
		SELECT *, CASE WHEN CAST(PAGO_TOTAL AS money) = 0 AND PAGOS_CARGA_HOY IS NULL THEN 1 ELSE 0 END AS CON_PAGO FROM (
		SELECT DESCUENTO_2.*, AJUSTE.TRX_NUMBER AS AJUSTE_RECIBO, OTROS.TRX_NUMBER AS OTROS_RECIBO, YAH.FECHA AS YAH_RECIBO FROM (
		SELECT * FROM (
		SELECT A.*, CON.ACCION AS ACCION_ACUMULADO  FROM #DESCUENTO_V3 A
		LEFT JOIN (
		SELECT * FROM (
		SELECT *, ROW_NUMBER () OVER (PARTITION BY RECIBO ORDER BY ACCION ASC, CAST(FECHA AS DATE) DESC) AS RANK_1 
		FROM CLARO.CONSOLIDADO_DESCUENTOS
		) AS DESCUENTO
		WHERE RANK_1 = 1) CON ON CON.RECIBO = A.RECIBO
												AND CON.CARTERA = A.CARTERA
												) AS DESCUENTO
												WHERE 
												ACCION_ACUMULADO IN('ofrecido') OR
												 ACCION_ACUMULADO IS NULL
												 ) AS DESCUENTO_2
		LEFT JOIN  [CLARO].[CLP_AJUSTES] AJUSTE ON AJUSTE.TRX_NUMBER = DESCUENTO_2.RECIBO
												--AND AJUSTE.NOMBRE_CARTERA = DESCUENTO_2.CARTERA
		
		LEFT JOIN  [CLARO].[CLP_AJUSTES_OTROS] OTROS ON OTROS.TRX_NUMBER = DESCUENTO_2.RECIBO
												--AND OTROS.NOMBRE_CARTERA = DESCUENTO_2.CARTERA

		LEFT JOIN CLARO.CONSOLIDADO_YAHAIRA YAH ON YAH.[NRO DOC] = DESCUENTO_2.RECIBO
		) AS CONCRETADO
		WHERE AJUSTE_RECIBO IS NULL 
		AND OTROS_RECIBO IS NULL
		AND YAH_RECIBO IS NULL
			) AS FINAL_CONCRETADO
			WHERE CON_PAGO = 0
			--AND RECIBO = 'SB02-0226175839'

				SELECT OFR.*, 
					   CON.ACCION AS ACCION_ACUMULADO,
					   YAH.FECHA AS YAH_RECIBO,
					   AJUSTE.TRX_NUMBER AS AJUSTE_RECIBO, 
					   OTROS.TRX_NUMBER AS OTROS_RECIBO,
					   CONCRETADO.RECIBO AS CONCRETADO,
					   PAGO.TRX_NUMBER AS PAGO
					   INTO #OFRECIDO
				FROM #DESCUENTO_V2 OFR
						LEFT JOIN CLARO.CONSOLIDADO_DESCUENTOS CON ON CON.RECIBO = OFR.RECIBO
												AND CON.CARTERA = OFR.CARTERA
						LEFT JOIN CLARO.CONSOLIDADO_YAHAIRA YAH ON YAH.[NRO DOC] = OFR.RECIBO			
						LEFT JOIN  [CLARO].[CLP_AJUSTES] AJUSTE ON AJUSTE.TRX_NUMBER = OFR.RECIBO
												--AND AJUSTE.NOMBRE_CARTERA = OFR.CARTERA
		
		LEFT JOIN  [CLARO].[CLP_AJUSTES_OTROS] OTROS ON OTROS.TRX_NUMBER = OFR.RECIBO
												--AND OTROS.NOMBRE_CARTERA = OFR.CARTERA
		LEFT JOIN #CONCRETADOS CONCRETADO ON CONCRETADO.RECIBO = OFR.RECIBO
											 AND CONCRETADO.CARTERA = OFR.CARTERA

		LEFT JOIN (	SELECT TRX_NUMBER, NOMBRE_CARTERA, SUM(CAST(AMOUNT_APPLIED_SOLES AS MONEY)) AS AMOUNT_APPLIED_SOLES FROM (	
						SELECT * FROM (
					SELECT A.*, PAGO_TOTAL  FROM (SELECT TRX_NUMBER, NOMBRE_CARTERA, 
														CAST(A.FECHA_PAGO_SISTEMA AS date) AS FECHA_PAGO_SISTEMA,
														SUM(CAST(AMOUNT_APPLIED_SOLES AS MONEY)) AS AMOUNT_APPLIED_SOLES 
														FROM CLARO.PAGOS A WITH(NOLOCK)
														WHERE A.FECHA_CARGA = CAST(GETDATE() AS DATE) 
														AND A.NOMBRE_CARTERA NOT LIKE '%PJ%'
														AND A.NOMBRE_CARTERA NOT LIKE '%P_M%'
														AND A.NOMBRE_CARTERA NOT LIKE '%WHATSAPP%'
														AND A.NOMBRE_CARTERA NOT LIKE '%P_FIJA%'
														AND A.NOMBRE_CARTERA NOT LIKE '%P_CVE%'
														
														GROUP BY TRX_NUMBER, NOMBRE_CARTERA, CAST(A.FECHA_PAGO_SISTEMA AS date)) A
					LEFT JOIN (SELECT RECIBO, CARTERA, PAGO_TOTAL, FECHA_PAGO  FROM #DESCUENTO_V2 WITH(NOLOCK)
								WHERE FECHA_PAGO IS NOT NULL
								AND CAST(PAGO_TOTAL AS MONEY) >0) RET ON RET.RECIBO = A.TRX_NUMBER
																		AND RET.CARTERA = A.NOMBRE_CARTERA
																		AND RET.PAGO_TOTAL = A.AMOUNT_APPLIED_SOLES
																		AND CAST(RET.FECHA_PAGO AS date) = CAST(A.FECHA_PAGO_SISTEMA AS date)

							) AS PAGOS_CLARO
							WHERE PAGO_TOTAL IS NULL
							) AS PAGO_UNIDO
							GROUP BY TRX_NUMBER, NOMBRE_CARTERA
							) PAGO ON PAGO.TRX_NUMBER =OFR.RECIBO
									AND PAGO.NOMBRE_CARTERA =OFR.CARTERA

				WHERE CAST(OFR.SALDO_SOLES AS MONEY) >= 5
				AND OFR.FECHA_PAGO IS NULL
				AND CAST(OFR.FECHA_FIN AS date) > CAST(GETDATE() AS date)
				AND CAST(OFR.FECHA_GESTION_DESDE_EL_INICIO_DE_CARTERA AS date) = CAST(GETDATE() AS date)
				AND OFR.FECHA_COMPROMISO_DESDE_EL_INICIO_DE_CARTERA IS NOT NULL
				AND CON.ACCION IS NULL
				AND YAH.FECHA IS NULL
				AND AJUSTE.TRX_NUMBER IS NULL 
				AND OTROS.TRX_NUMBER IS NULL
				AND CONCRETADO.RECIBO IS NULL
				AND CONCRETADO.RECIBO IS NULL
				AND PAGO.TRX_NUMBER IS NULL


UPDATE #CONCRETADOS
SET AJUSTE_REALIZADO = SALDOS_SOLES_FINAL
WHERE AJUSTE_REALIZADO IS NULL
	
UPDATE 	#CONCRETADOS
SET ACCION = 'Concretado'

UPDATE 	#CONCRETADOS
SET [OBSERVACIONES] = 'APLICA DESCUENTO'

UPDATE 	#CONCRETADOS
SET [FECHA_REGISTRO] =  FORMAT(GETDATE(),'d/MM/yyyy')

UPDATE #CONCRETADOS
SET MONTO_PAGADO = CAST(PAGO_TOTAL AS money) + ISNULL(CAST(PAGOS_CARGA_HOY AS money),0)

UPDATE #CONCRETADOS
SET FECHA = FORMAT(GETDATE(),'d/MM/yyyy')

UPDATE #CONCRETADOS
SET ACEPTO = 'SI'

UPDATE 	#OFRECIDO
SET ACCION = 'Ofrecido'

UPDATE 	#OFRECIDO
SET [OBSERVACIONES] = 'NO PAGO DEUDA/NO APLICA DESCUENTO'

UPDATE #OFRECIDO
SET ACEPTO = 'SI'

UPDATE #OFRECIDO
SET FECHA = FORMAT(GETDATE(),'d/MM/yyyy')


SELECT FINAL.* INTO ##DESCUENTO_FINAL
FROM (
SELECT  
		[FECHA] AS [FECHA],
		[MES] AS [MES],
		[AÑO] AS [AÑO],
		[CUST_ACCOUNT_ASIGNACION] AS [CUENTA],
		[RUC_DNI_ASIGNACION] AS [DNI],
		[NOMBRE_COMPLETO] AS [Nombres],
		[SERVICIO] AS [SERVICIO],
		[TECNOLOGIA] AS [TECNOLOGIA],
		[RECIBO] AS [RECIBO],
		[FECHA_EMISION] AS [Emisión],
		[FECHA_VENCIMIENTO] AS [Vencimiento],
		[IMPORTE_FACTURADO] AS [Importe Facturado],
		[SALDO_GESTIONADO] AS [SALDO_GESTIONADO],
		[ETAPA] AS [ETAPA],
		[GESTOR] AS [GESTOR],
		[CARTERA] AS [CARTERA],
		[DESCUENTO] AS [MONTO_AJUSTE_OFRECIDO],
		[MONTO_PAGADO] AS [MONTO_PAGADO],
		[SERVICIO_PLAN] AS [SERVICIO_PLAN],
		[ANTIGUEDAD] AS [ANTIGÜEDAD],
		[ACEPTO] AS [ACEPTO],
		[AJUSTE_REALIZADO] AS [AJUSTE REALIZADO],
		[FECHA_REGISTRO] AS [FECHA_REGISTRO],
		[OBSERVACIONES] AS [OBSERVACIONES],
		[BENEFICIO] AS [BENEFICIO],
		[DOC_DEFINITIVO] AS [Doc_Definitivo],
		[ACCION] AS [ACCION],
		[FECHA_FIN] AS [FECHA_FIN]




FROM #OFRECIDO
WHERE SERVICIO != 'FIJA'


 
UNION ALL

SELECT 
		[FECHA] AS [FECHA],
		[MES] AS [MES],
		[AÑO] AS [AÑO],
		[CUST_ACCOUNT_ASIGNACION] AS [CUENTA],
		[RUC_DNI_ASIGNACION] AS [DNI],
		[NOMBRE_COMPLETO] AS [Nombres],
		[SERVICIO] AS [SERVICIO],
		[TECNOLOGIA] AS [TECNOLOGIA],
		[RECIBO] AS [RECIBO],
		[FECHA_EMISION] AS [Emisión],
		[FECHA_VENCIMIENTO] AS [Vencimiento],
		[IMPORTE_FACTURADO] AS [Importe Facturado],
		[SALDO_GESTIONADO] AS [SALDO_GESTIONADO],
		[ETAPA] AS [ETAPA],
		[GESTOR] AS [GESTOR],
		[CARTERA] AS [CARTERA],
		[DESCUENTO] AS [MONTO_AJUSTE_OFRECIDO],
		[MONTO_PAGADO] AS [MONTO_PAGADO],
		[SERVICIO_PLAN] AS [SERVICIO_PLAN],
		[ANTIGUEDAD] AS [ANTIGÜEDAD],
		[ACEPTO] AS [ACEPTO],
		[AJUSTE_REALIZADO] AS [AJUSTE REALIZADO],
		[FECHA_REGISTRO] AS [FECHA_REGISTRO],
		[OBSERVACIONES] AS [OBSERVACIONES],
		[BENEFICIO] AS [BENEFICIO],
		[DOC_DEFINITIVO] AS [Doc_Definitivo],
		[ACCION] AS [ACCION],
		[FECHA_FIN] AS [FECHA_FIN]

FROM 


(SELECT *, ISNULL(CAST(SALDO_GESTIONADO AS money),0)
			- (ISNULL(CAST([MONTO_PAGADO] AS money),0) + ISNULL(CAST([AJUSTE_REALIZADO] AS money),0)) AS VALIDACION_FINAL FROM #CONCRETADOS ) AS CONCRETADOS

INNER JOIN (SELECT DISTINCT TRX_NUMBER,NOMBRE_CARTERA FROM CLARO.PAGOS WITH(NOLOCK) 
			WHERE FECHA_CARGA >= (SELECT MIN(CAST(FECHA_INI AS DATE))  FROM #DESCUENTO_V2)) 
			PAG ON PAG.TRX_NUMBER = CONCRETADOS.[RECIBO]
				AND PAG.NOMBRE_CARTERA = CONCRETADOS.[CARTERA]

--WHERE SERVICIO != 'FIJA'

WHERE VALIDACION_FINAL <= 2
AND  [RUC_DNI_ASIGNACION] != '71553937'
AND SERVICIO != 'FIJA'

) AS FINAL
INNER JOIN (SELECT * FROM (
			SELECT *, ROW_NUMBER() OVER(PARTITION BY CODIGO, NOMBRE_CARTERA ORDER BY CODIGO DESC) AS ESTADO_RANK FROM #CLP_ESTADOS) AS SUB_QUERY
			WHERE ESTADO_RANK = 1
			AND ESTADO_SERVICIO != 'Desactivo') EST ON EST.CODIGO = FINAL.[CUENTA]
											AND EST.NOMBRE_CARTERA = FINAL.[CARTERA]



SELECT 
		[FECHA] AS [FECHA],
		[MES] AS [MES],
		[AÑO] AS [AÑO],
		[CUST_ACCOUNT_ASIGNACION] AS [CUENTA],
		[RUC_DNI_ASIGNACION] AS [DNI],
		[NOMBRE_COMPLETO] AS [Nombres],
		[SERVICIO] AS [SERVICIO],
		[TECNOLOGIA] AS [TECNOLOGIA],
		[RECIBO] AS [RECIBO],
		[FECHA_EMISION] AS [Emisión],
		[FECHA_VENCIMIENTO] AS [Vencimiento],
		[IMPORTE_FACTURADO] AS [Importe Facturado],
		[SALDO_GESTIONADO] AS [SALDO_GESTIONADO],
		[ETAPA] AS [ETAPA],
		[GESTOR] AS [GESTOR],
		[CARTERA] AS [CARTERA],
		[DESCUENTO] AS [MONTO_AJUSTE_OFRECIDO],
		[MONTO_PAGADO] AS [MONTO_PAGADO],
		[SERVICIO_PLAN] AS [SERVICIO_PLAN],
		[ANTIGUEDAD] AS [ANTIGÜEDAD],
		[ACEPTO] AS [ACEPTO],
		[AJUSTE_REALIZADO] AS [AJUSTE REALIZADO],
		[FECHA_REGISTRO] AS [FECHA_REGISTRO],
		[OBSERVACIONES] AS [OBSERVACIONES],
		[BENEFICIO] AS [BENEFICIO],
		[DOC_DEFINITIVO] AS [Doc_Definitivo],
		[ACCION] AS [ACCION],
		[FECHA_FIN] AS [FECHA_FIN]
		
		INTO ##NO_CUMPLE_CONCRETADO
FROM 

(SELECT *, ISNULL(CAST(SALDO_GESTIONADO AS money),0)
			- (ISNULL(CAST([MONTO_PAGADO] AS money),0) + ISNULL(CAST([AJUSTE_REALIZADO] AS money),0)) AS VALIDACION_FINAL FROM #CONCRETADOS ) AS CONCRETADOS
WHERE VALIDACION_FINAL > 2




SELECT 
		*
		INTO ##AGENTE_CONCRETADO
FROM 

(SELECT *, ISNULL(CAST(SALDO_GESTIONADO AS money),0)
			- (ISNULL(CAST([MONTO_PAGADO] AS money),0) + ISNULL(CAST([AJUSTE_REALIZADO] AS money),0)) AS VALIDACION_FINAL FROM #CONCRETADOS ) AS CONCRETADOS
WHERE VALIDACION_FINAL <= 2


		DECLARE @FEC_FIN DATE = GETDATE();
		DECLARE @FEC_MES DATE;
		DECLARE @FEC_INI DATE;

		-- Fecha de inicio del año actual
		SET @FEC_INI = DATEFROMPARTS(YEAR(@FEC_FIN), 1, 1);

		-- Fecha del primer día del mes de @FEC_FIN
		SET @FEC_MES = DATEADD(DAY, 1, EOMONTH(@FEC_INI, -1));




	 /*===================================    
		   = SE GENERA EXCEL =   
    ===================================*/ 

	DECLARE   
			@_ARCHIVO		VARCHAR(8000),  
			@_RECIPIENTS	VARCHAR(400),  
			@TITULO		    VARCHAR(1000),  
			@_MESSAGE		VARCHAR(8000),  
			@SUBJECT		NVARCHAR(400),
            @SQL            NVARCHAR(400)


	BEGIN

		SET @_ARCHIVO = 'T:\RUTA_PROYECTO\PROCESO DESCUENTO\DESCUENTO_FINAL_' + CONVERT(VARCHAR, @FEC_FIN, 112) + '_AL_'  + CONVERT(VARCHAR, @FEC_FIN, 112) + '.xlsx'  
  
		SET @SQL = ' SELECT * FROM ##DESCUENTO_FINAL'

  
		EXEC [COBRANZA]..S_HACE_XLS @_ARCHIVO OUT, @SQL 

		
		SET @_ARCHIVO = 'T:\RUTA_PROYECTO\PROCESO DESCUENTO\CONCRETADO_AGENTE' + CONVERT(VARCHAR, @FEC_FIN, 112) + '_AL_'  + CONVERT(VARCHAR, @FEC_FIN, 112) + '.xlsx'  
  
		SET @SQL = ' SELECT * FROM ##AGENTE_CONCRETADO
					 '  
  
		EXEC [COBRANZA]..S_HACE_XLS @_ARCHIVO OUT, @SQL 

		
		SET @_ARCHIVO = 'T:\RUTA_PROYECTO\PROCESO DESCUENTO\CONCRETADO_NO_CUMPLE_' + CONVERT(VARCHAR, @FEC_FIN, 112) + '_AL_'  + CONVERT(VARCHAR, @FEC_FIN, 112) + '.xlsx'  
  
		SET @SQL = ' SELECT * FROM ##NO_CUMPLE_CONCRETADO 
					'  
  
		EXEC [COBRANZA]..S_HACE_XLS @_ARCHIVO OUT, @SQL 

	END


		IF OBJECT_ID('tempdb..##CLP_TXT_DESCUENTO','U') IS NOT NULL
DROP TABLE ##CLP_TXT_DESCUENTO

CREATE TABLE ##CLP_TXT_DESCUENTO ( COLUMNA VARCHAR(8000), ORDEN TINYINT )

	INSERT INTO ##CLP_TXT_DESCUENTO VALUES ( 'G_CUENTA|G_RECIBO|G_GESTOR|G_CARTERA|G_MONTO_AJUSTE_OFRECIDO|G_ACEPTO|G_ACCION', 1)


	INSERT INTO ##CLP_TXT_DESCUENTO
	SELECT DISTINCT 
			   LTRIM(RTRIM(ISNULL(CONVERT(VARCHAR, [CUENTA]), '')))  
    + '|' + LTRIM(RTRIM(ISNULL(CONVERT(VARCHAR, [RECIBO]), '')))  
    + '|' + LTRIM(RTRIM(ISNULL(CONVERT(VARCHAR, 'IBR'), '')))  
    + '|' + LTRIM(RTRIM(ISNULL(CONVERT(VARCHAR, [CARTERA]), '')))  
    + '|' + LTRIM(RTRIM(ISNULL(CONVERT(VARCHAR, [MONTO_AJUSTE_OFRECIDO]), '')))  
    + '|' + LTRIM(RTRIM(ISNULL(CONVERT(VARCHAR, 'SI'), '')))  
	+ '|' + LTRIM(RTRIM(ISNULL(UPPER(CONVERT(VARCHAR, ACCION)), ''))) AS COLUMNA,
		2 
--SELECT *
	FROM ##DESCUENTO_FINAL
	

	
DECLARE @CMD VARCHAR(1000)
DECLARE @ARCHIVO VARCHAR(100)
DECLARE @RUTA_LOCAL VARCHAR(100)
DECLARE @RUTA_SFTP VARCHAR(100)
DECLARE @ARCHIVO_SFTP VARCHAR(100)
DECLARE @EXTENSION VARCHAR(10)

-- Definir las rutas de archivo
SET @RUTA_LOCAL = 'T:\RUTA_PROYECTO\PROCESO DESCUENTO\'
SET @RUTA_SFTP = '/files/Dscto_Fidel/'
SET @EXTENSION = '.txt'

-- Construir el nombre del archivo
SET @ARCHIVO = 'Dscto_Fidel_IBR_' +  FORMAT(CAST( GETDATE() AS DATE),'yyyyMMdd') + @EXTENSION

SET @CMD = 'bcp "SELECT COLUMNA FROM ##CLP_TXT_DESCUENTO ORDER BY ORDEN ASC " queryout "' + @RUTA_LOCAL + @ARCHIVO + '" -c -t, -U USUARIO_DB -P PASSWORD_DB -S SERVIDOR_DB'
-- Ejecutar el comando bcp
EXEC xp_cmdshell @CMD


-- Construir el comando para transferir el archivo al servidor SFTP usando curl
SET @ARCHIVO_SFTP = 'Dscto_Fidel_IBR_' +  FORMAT(CAST( GETDATE() AS DATE),'yyyyMMdd') + @EXTENSION

SET @CMD = 'C:\curl\bin\curl --insecure -T "' + @RUTA_LOCAL + @ARCHIVO + '" "sftp://USUARIO_SFTP:PASSWORD_SFTP@IP_SERVIDOR_SFTP/' + @RUTA_SFTP + @ARCHIVO_SFTP + '"'
-- Ejecutar el comando curl para transferir el archivo a SFTP
EXEC xp_cmdshell @CMD


		END




		END
